### ISSUE TITLE
Some error when you render the new MD files

### ISSUE THREAD

**Issue by bgruening** [hexylena/docker-rstudio-notebook#39]
I'm not sure this is our fault, but documenting it here. Maybe someone has an idea.

```
ERROR: PermissionDenied: Permission denied (os error 13)

PermissionDenied: Permission denied (os error 13)
    at makeTempDirSync (deno:runtime/js/30_fs.js:80:16)
    at file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:5958:29
    at withAttempts (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:5917:20)
    at Object.makeTempDirSync (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:5958:12)
    at initSessionTempDir (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:47815:20)
    at quarto (file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:127537:5)
    at file:///usr/lib/rstudio-server/bin/quarto/bin/quarto.js:127557:15
``

**Comment by bgruening** [comment]
https://github.com/quarto-dev/quarto-cli/issues/4594 seems related.

**Comment by bgruening** [comment]
Its actually not that. Its wrong permissions in the container. 

> chmod 777 \$TMPDIR &&

as part of the XML is fixing it. https://github.com/usegalaxy-eu/galaxy/commit/f42292f8c20cacca30dd117779836ee769caf703
